import type { NextPage } from "next";
import Head from "next/head";
import { Provider } from "react-redux";
import Posts from "../components/Posts";
import { setUpStore } from "../store/store";
import styles from "../styles/Home.module.css";

// const store = setUpStore();

// const store = useMemo(() => setUpStore(), []);

const Home: NextPage = () => {
  return (
    // <Provider store={store}>
    <div className={styles.container}>
      <Head>
        <title>Only Next</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Posts />
    </div>
    // </Provider>
  );
};

export default Home;
